# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160928_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='aside',
            field=wagtail.wagtailcore.fields.StreamField((('alert', wagtail.wagtailcore.blocks.RichTextBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), help_text="Sidebar content, intended for 'call 999 if...' alerts"),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('callout', wagtail.wagtailcore.blocks.RichTextBlock(help_text='Block to draw users\' attention, e.g. for "See your GP"', label='Callout block')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(label='Text')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('subsections', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock(label='Text')))))))))), label='Page section')))),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='intro',
            field=models.CharField(help_text='Introductory text below header', max_length=255),
        ),
    ]
